server:
  storageFolder: ./data
template:
  source: cedar
  api_key: 6016177645f66555aa2e90fdfa523036127f586c731b8275158759921c21b304
  templateId: e1c5e285-a2e6-43df-9bfa-1de71f6a59e3
  storage: local
  instance_base_url: http://localhost
  title_predicate: title
bioportal:
  api_key: my_api_key
tableColumns:
  - property: "General Model Information.Title"
    label: "Title"
    linkable: true
  - property: "General Model Information.Created by"
    label: "Author"
  - property: "General Model Information.Creation date"
    label: "Date created"
  - property: "General Model Information.Developed at CDS (Maastro)"
    label: "Organisation"