server:
  storageFolder: ./data
  server_url: "http://rdf-store:7200"
  repository_name: "semantic_forms"
  update_endpoint_suffix: "/statements"
template:
  source: cedar
  templateId: e1c5e285-a2e6-43df-9bfa-1de71f6a59e3
  storage: cedar
  instance_base_url: https://describe.fairmodels.org/instance
  title_predicate: http://purl.org/dc/terms/title
