version: '3.8'
services:
  rdf-store:
    image: ghcr.io/maastrichtu-cds/fair_tools_docker-graphdb/docker-graphdb:latest
    ports: 
      - "7200:7200"
    environment:
      - GDB_HEAP_SIZE=2g
      - GDB_MIN_MEM=1g
      - GDB_MAX_MEM=2g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7200/repositories"]
      interval: 5s
      timeout: 3s
      retries: 5
  semforms:
    image: ghcr.io/maastrichtu-biss/semanticforms:sprint
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./src/config.yaml:/app/config.yaml
      # - ./src/run.py:/app/run.py
      # - ./src/endpoint_service.py:/app/endpoint_service.py
      # - ./src/templates/cee.html:/app/templates/cee.html
    depends_on:
      rdf-store:
        condition: service_healthy
