services:
  # rdf-store:
  #   image: ghcr.io/maastrichtu-cds/fair_tools_docker-graphdb/docker-graphdb:latest
  #   ports: 
  #     - "7200:7200"
  #   environment:
  #     - GDB_HEAP_SIZE=2g
  #     - GDB_MIN_MEM=1g
  #     - GDB_MAX_MEM=2g
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:7200/repositories"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 5
  semforms:
    image: ghcr.io/maastrichtu-biss/semanticforms:2
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - semforms_data:/app/data
      - ./src/config.yaml:/app/config.yaml
      - ./.env:/app/.env
    depends_on:
      rdf-store:
        condition: service_healthy
  postgres:
    image: postgres:17.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
    networks:
      - keycloak_network

volumes:
  postgres_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge
