version: '3.8'
services:
  rdf-store:
    image: ontotext/graphdb:10.4.2
    ports: 
      - "127.0.0.1:7200:7200"
    volumes:
      - graphdb_data:/opt/graphdb/home
    restart: unless-stopped
    environment:
      - GDB_HEAP_SIZE=2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7200/repositories"]
      interval: 5s
      timeout: 3s
      retries: 5
  semforms:
    image: ghcr.io/maastrichtu-biss/semanticforms
    restart: unless-stopped
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - semforms_data:/app/data
      - ./src/config.yaml:/app/config.yaml
    depends_on:
      rdf-store:
        condition: service_healthy
volumes:
  graphdb_data:
  semforms_data:
