server:
  storageFolder: ./data
  rdf_endpoint: http://localhost:7200/repositories/public_dump
  rdf_endpoint_update: http://localhost:7200/repositories/public_dump/statements
template:
  source: file
  location: template.json
  instance_base_url: http://localhost/template-instances