server:
  storageFolder: ../data
#   server_url: "https://graphdb.fairmodels.org"
#   repository_name: "semantic_forms"
#   update_endpoint_suffix: "/statements"
ontology_path:
  - ../ROO.owl
template:
  source: cedar
  templateId: bf75c936-ba23-468a-80dd-4fe1be6714ed
  storage: local
  instance_base_url: http://localhost
  title_predicate: http://purl.org/dc/terms/title