server:
  storageFolder: ../data
#   server_url: "https://graphdb.fairmodels.org"
#   repository_name: "semantic_forms"
#   update_endpoint_suffix: "/statements"
template:
  source: cedar
  templateId: 2781be7e-b18f-45d0-9c89-014c01f2ddf7
  storage: local
  instance_base_url: http://localhost
  title_predicate: title
tableColumns:
  - property: "title"
    label: "Title"
  - property: "status"
    label: "Status"
  - property: "date_created"
    label: "Created On"
  - property: "author"
    label: "Author"