server:
  storageFolder: ./data
  server_url: "http://rdf-store:7200"
  repository_name: "semantic_forms"
  update_endpoint_suffix: "/statements"
template:
  source: file
  location: template.json
  instance_base_url: http://localhost/template-instances