name: Build WebUI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - '**'

env:
  REGISTRY: ghcr.io

jobs:
  containerize:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      ## Check this thread to solve this issue
      ## https://stackoverflow.com/questions/57549439/how-do-i-use-docker-with-github-actions
      - name: Build frontend
        id: build_frontend
        run: |
          cd cee
          NODE_VERSION=16
          docker volume create node-$NODE_VERSION-cedar-build
          rm -Rf $(pwd)/output
          docker run --rm -it -v $(pwd)/input:/input -v $(pwd)/output:/output -v node-$NODE_VERSION-cedar-build:/build node:$NODE_VERSION-bullseye /bin/bash /input/build_frontend.sh
          cat output/{runtime,polyfills,main}.js > "../src/static/cee/cedar-embeddable-editor.js"
          docker run --rm -it -v $(pwd)/output:/output --workdir /output node:$NODE_VERSION-bullseye npm install @webcomponents/webcomponentsjs
          cp -R output/node_modules ../src/static/cee/node_modules
          cp output/{MaterialIcons-*,styles.css} ../src/static/cee/
      - name: Build container
        id: docker_build
        uses: docker/build-push-action@v2
        if: steps.extract_branch.outputs.branch != 'main'
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ steps.extract_branch.outputs.branch }}
      - name: Build container
        id: docker_build_main
        uses: docker/build-push-action@v2
        if: steps.extract_branch.outputs.branch == 'main'
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ steps.extract_branch.outputs.branch }}, ghcr.io/${{ env.REPO }}:latest